In [2]:
import numpy as np 

In [7]:
n, m = 3, 4
v = np.random.rand(n)
Psi = np.random.rand(m, n, n)  # Random stack of 3x3 matrices

# Compute B using einsum
B_einsum = -np.einsum('ijk,k->ji', Psi, v)

# Manual computation for comparison
B_manual = np.array([-Psi[j] @ v for j in range(m)]).T

# Check if B_einsum and B_manual are equivalent
print("B_einsum:\n", B_einsum)
print("B_manual (Transpose of comprehension result):\n", B_manual)
print("Are both methods equivalent?", np.array_equal(B_einsum, B_manual))

B_einsum:
 [[-0.18472169 -0.2334723  -0.15250356 -0.19478539]
 [-0.26355929 -0.269839   -0.42922997 -0.22708973]
 [-0.13359298 -0.14285972 -0.18581527 -0.40530016]]
B_manual (Transpose of comprehension result):
 [[-0.18472169 -0.2334723  -0.15250356 -0.19478539]
 [-0.26355929 -0.269839   -0.42922997 -0.22708973]
 [-0.13359298 -0.14285972 -0.18581527 -0.40530016]]
Are both methods equivalent? False


In [9]:
np.linalg.norm(B_manual - B_einsum)

np.float64(3.925231146709438e-17)

In [42]:
n = 3  # Dimension of matrices and vector
m = 4  # Number of matrices and scalars in u

# Randomly generate matrices and vectors
Psi = np.random.rand(m, n, n)  # Stack of m n x n matrices
x = np.random.rand(n)          # n-dimensional vector
u = np.random.rand(m)          # m-dimensional vector (scalars u_j)

# Compute the weighted sum of matrices
# 'ijk,j->ik' reads as: take the ijk-th element of Psi and the j-th element of u, 
# multiply them, and then sum over j to produce an ik matrix
weighted_sum = np.einsum('ijk,i->jk', Psi, u)

# Multiply the resulting matrix by vector x
result = np.dot(weighted_sum, x)

np.einsum('ijk,i->jk', Psi, u) - np.sum([Psi[j] * u[j] for j in range(m)], axis=0)

array([[0.00000000e+00, 0.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])